name: flutter_fimber_filelogger
description: A file logger tree for Flutter Fimber (which includes an auto-clean mechanism)
version: 1.1.1+1
author: Edouard Marquez <moi@edouard-marquez.me>
homepage: https://github.com/g123k/flutter_fimber_filelogger

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_fimber: ^0.4.4

  path_provider: ^1.6.11
  intl: ^0.16.1
  path: ^1.7.0
  synchronized: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: